/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.*;
import java.util.*;
import javax.swing.*;
import model.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;


public class GameGUI extends javax.swing.JFrame {
    ControlQuiz quiz;
    ArrayList<Player> players;
    Game selectedGame;
    WordPair tempWp;
     int difficulty, currentPlayerNum;
     Random rng;
     ImageIcon imageRight = new ImageIcon("Extra/happy.jpg");
     ImageIcon imageWrong = new ImageIcon("Extra/mille.jpg");
     ImageIcon imageNeutral = new ImageIcon("Extra/haandbold.jpg");

    public GameGUI(ControlQuiz quiz, ArrayList<Player> players, int difficulty) {
        initComponents();
        rng = new Random();
        this.quiz = quiz;
        this.players = players;
        this.difficulty = difficulty;
        this.selectedGame = quiz.getSelectedGame();
        this.currentPlayerNum = rng.nextInt(players.size());
        jLabelGameTitle.setText(selectedGame.getTitle());
        jLabelFlavorAnswer.setText(selectedGame.getGuiAnswer());
        jLabelFlavorQuestion.setText(selectedGame.getGuiQuestion());
        jButtonNewQuestionActionPerformed(null); // New Question
        setVisible(true);
        setLocationRelativeTo(null);
        initPlayers();
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception ex){}
    }
    
    public void CallMenuGUI() {
        new MenuGUI(quiz);
        dispose();
    }
    
    public void initPlayers()
    {
        DefaultTableModel model = (DefaultTableModel) jTableStats.getModel();
        model.setRowCount(players.size());
        for (int i = 0; i < players.size(); i++){
            Player temp = players.get(i);
            model.setValueAt(temp.getName(), i, 0);
            model.setValueAt(temp.getPoints(), i, 1);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelLanguageLearning = new javax.swing.JPanel();
        jLabelGameTitle = new javax.swing.JLabel();
        jLabelFlavorQuestion = new javax.swing.JLabel();
        jTextFieldQuestion = new javax.swing.JTextField();
        jLabelFlavorAnswer = new javax.swing.JLabel();
        jTextFieldAnswer = new javax.swing.JTextField();
        jTextFieldResult = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButtonGuess = new javax.swing.JButton();
        jButtonNewQuestion = new javax.swing.JButton();
        jPanelOuterStats = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableStats = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabelplayerName = new javax.swing.JLabel();
        jLabelPicture = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Game Window");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelLanguageLearning.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelGameTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelGameTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelGameTitle.setText("GAME TITLE HERE");
        jPanelLanguageLearning.add(jLabelGameTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 304, 38));

        jLabelFlavorQuestion.setText("Question:");
        jPanelLanguageLearning.add(jLabelFlavorQuestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 50, -1));

        jTextFieldQuestion.setEditable(false);
        jPanelLanguageLearning.add(jTextFieldQuestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 400, -1));

        jLabelFlavorAnswer.setText("Answer:");
        jPanelLanguageLearning.add(jLabelFlavorAnswer, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 50, -1));
        jPanelLanguageLearning.add(jTextFieldAnswer, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 400, -1));

        jTextFieldResult.setEditable(false);
        jTextFieldResult.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jPanelLanguageLearning.add(jTextFieldResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 400, -1));

        jLabel7.setText("Result:");
        jPanelLanguageLearning.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 50, -1));

        jButtonGuess.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonGuess.setText("Guess!");
        jButtonGuess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuessActionPerformed(evt);
            }
        });
        jPanelLanguageLearning.add(jButtonGuess, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 190, -1));

        jButtonNewQuestion.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButtonNewQuestion.setText("New Question");
        jButtonNewQuestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewQuestionActionPerformed(evt);
            }
        });
        jPanelLanguageLearning.add(jButtonNewQuestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 190, -1));

        jPanelOuterStats.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Player Stats")));

        jTableStats.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "Name", "Points"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableStats.setEnabled(false);
        jScrollPane1.setViewportView(jTableStats);

        javax.swing.GroupLayout jPanelOuterStatsLayout = new javax.swing.GroupLayout(jPanelOuterStats);
        jPanelOuterStats.setLayout(jPanelOuterStatsLayout);
        jPanelOuterStatsLayout.setHorizontalGroup(
            jPanelOuterStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelOuterStatsLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelOuterStatsLayout.setVerticalGroup(
            jPanelOuterStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelOuterStatsLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanelLanguageLearning.add(jPanelOuterStats, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, 220, 320));

        jLabel1.setText("Current Player:");
        jPanelLanguageLearning.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabelplayerName.setText("playerName");
        jPanelLanguageLearning.add(jLabelplayerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, -1));
        jPanelLanguageLearning.add(jLabelPicture, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 0, -1));

        getContentPane().add(jPanelLanguageLearning, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGuessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuessActionPerformed
        String guess = jTextFieldAnswer.getText();
        String answer = tempWp.getAnswer();
        Player tempPlayer = players.get(currentPlayerNum);
        
        if (guess.equalsIgnoreCase(answer)){
            tempPlayer.addPoint();
            jTextFieldResult.setText("Correct!");
            jLabelPicture.setIcon(imageRight);
        }else{
            jTextFieldResult.setText("Wrong guess! Real Answer: " + answer);
            jLabelPicture.setIcon(imageWrong);
            currentPlayerNum++;
            if (currentPlayerNum >= players.size()){
                currentPlayerNum = 0;
            }
        }
        jButtonGuess.setEnabled(false);
        jButtonNewQuestion.setEnabled(true);
        initPlayers();
    }//GEN-LAST:event_jButtonGuessActionPerformed

    private void jButtonNewQuestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewQuestionActionPerformed
        jLabelPicture.setIcon(imageNeutral);
        jLabelplayerName.setText(players.get(currentPlayerNum).getName());
        tempWp = selectedGame.getRandomWordPair();
        jTextFieldQuestion.setText(tempWp.getQuestion());
        jTextFieldAnswer.setText("");
        jButtonGuess.setEnabled(true);
        jButtonNewQuestion.setEnabled(false);
    }//GEN-LAST:event_jButtonNewQuestionActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGuess;
    private javax.swing.JButton jButtonNewQuestion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelFlavorAnswer;
    private javax.swing.JLabel jLabelFlavorQuestion;
    private javax.swing.JLabel jLabelGameTitle;
    private javax.swing.JLabel jLabelPicture;
    private javax.swing.JLabel jLabelplayerName;
    private javax.swing.JPanel jPanelLanguageLearning;
    private javax.swing.JPanel jPanelOuterStats;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableStats;
    private javax.swing.JTextField jTextFieldAnswer;
    private javax.swing.JTextField jTextFieldQuestion;
    private javax.swing.JTextField jTextFieldResult;
    // End of variables declaration//GEN-END:variables
}
